<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>isso__icon__login_top</name>
   <tag></tag>
   <elementGuidId>6fa9595c-c5a5-4576-b637-8c5ddd830e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sso__icon__login_top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='sso__icon__login_top']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>04d9e9c5-b54b-491c-9cbb-373e647c2898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sso__icon__login</value>
      <webElementGuid>37a512e5-d20e-4006-9861-851f3aeac72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sso__icon__login_top</value>
      <webElementGuid>d581c5eb-9c76-4640-8ff0-b932d5636459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sso__icon__login_top&quot;)</value>
      <webElementGuid>18466c32-1a92-431b-91a4-690ed8ef3b7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='sso__icon__login_top']</value>
      <webElementGuid>eeac8723-aa80-4b45-86b3-8ba96840bd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>583d57ad-e4ac-4a3e-9553-a2fa8841be80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'sso__icon__login_top']</value>
      <webElementGuid>1cfd9ec0-94a6-48b7-b121-2540bf611cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
