<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>77947344-23fb-4d07-8074-a7d68397809b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_signin > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='txt_signin']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b85cb5cd-39b7-41b3-bdcc-ac840037bc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login</value>
      <webElementGuid>d0e63323-7897-4a34-be04-ed5e6b9da018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_signin&quot;)/span[1]</value>
      <webElementGuid>25299035-5687-4ca6-b87c-0fe2ed27a8a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='txt_signin']/span</value>
      <webElementGuid>df513482-cf0b-43d0-aae2-ae142d2943a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span</value>
      <webElementGuid>7814676c-f9ba-4166-b4b7-9d1a6aca45f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Login' or . = ' Login')]</value>
      <webElementGuid>bfdd150e-0eae-49ff-8f94-54f8ad508285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
