<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>54e30339-3d0e-4316-8e11-e79fd8fd40a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;view&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1f00fc37-12b0-4191-91d7-a4c62033ba3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://asset.kompas.com/data/2020/widget/ssonew/asset/images/icon-view.png</value>
      <webElementGuid>2c0cfba5-4af6-4024-a930-3bce960d08c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>view</value>
      <webElementGuid>30c014dc-fd60-4e94-a05f-a0446eaaead2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;block-middle&quot;]/div[@class=&quot;form-main&quot;]/form[1]/div[@class=&quot;form-row form-input&quot;]/button[@class=&quot;form-view icon-view js-view&quot;]/img[1]</value>
      <webElementGuid>79881517-e44f-4d93-8bc3-e0343ff9336c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='view']</value>
      <webElementGuid>54b00adc-4568-4b3f-ba80-4d1b68bb92ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>f029f8b5-3ec0-43e8-9620-c51d6309beec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://asset.kompas.com/data/2020/widget/ssonew/asset/images/icon-view.png' and @alt = 'view']</value>
      <webElementGuid>41e5ad78-4d1f-4474-b38f-5f03f1f80c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
