<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_2</name>
   <tag></tag>
   <elementGuidId>94f51e06-8ed4-44d2-9336-fa373129be8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4725f90c-76c1-4493-8d96-18695a386cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gsc-cursor-page</value>
      <webElementGuid>ece0c2a4-2b85-49c4-a501-c40fb40a0a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Page 2</value>
      <webElementGuid>d2467ce1-03e3-4922-b857-811e2aca1ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>bc7b5358-344b-436d-80b9-5b0da85d0f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de8451cb-2418-47bc-be48-5ab48222b3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5b21f2b9-167f-4d36-aff1-eff25d47583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-cursor-box gs-bidi-start-align&quot;]/div[@class=&quot;gsc-cursor&quot;]/div[@class=&quot;gsc-cursor-page&quot;]</value>
      <webElementGuid>c76fb392-e921-4927-8345-e00b9ea7861d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>e013eed6-3ab2-427a-bcd5-ada51aa8ff15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]</value>
      <webElementGuid>a1123ce7-af10-4feb-8f9d-ffdcac675e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2' or . = '2')]</value>
      <webElementGuid>bc6a6604-5158-4759-8186-4af47bbefbcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
